"""add_service_category_and_appointment_service_id

Revision ID: bac78a7d1a7d
Revises: 8cd0a74c2ae2
Create Date: 2026-02-02 17:03:21.419294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bac78a7d1a7d'
down_revision: Union[str, None] = '8cd0a74c2ae2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('service_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'appointments', 'services', ['service_id'], ['id'], ondelete='SET NULL')
    op.add_column('services', sa.Column('category', sa.String(length=50), nullable=True))
    op.add_column('services', sa.Column('sort_order', sa.Integer(), nullable=True))
    # Для существующих записей — значения по умолчанию
    op.execute("UPDATE services SET category = 'therapy' WHERE category IS NULL")
    op.execute("UPDATE services SET sort_order = 0 WHERE sort_order IS NULL")
    op.alter_column('services', 'category', nullable=False)
    op.alter_column('services', 'sort_order', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'sort_order')
    op.drop_column('services', 'category')
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_column('appointments', 'service_id')
    # ### end Alembic commands ###

